import catalog from '../data/official-benefits.json';
import status from '../data/benefit-status.json';
import {compareBenefits} from './benefits';
import {money,normalize} from './finance';
export const fixedCostCategories=['통신','주거','공과금','보험','구독','멤버십','교육','기타'];
export const paymentMethods=['카드 자동결제','공식 홈페이지 정기결제','앱스토어 결제','네이버페이','KB Pay','자동납부','잘 모르겠음'];
const categoryAliases={'넷플릭스':'구독','유튜브 프리미엄':'구독','티빙':'구독','웨이브':'구독','디즈니+':'구독','쿠팡 로켓와우':'멤버십','네이버플러스':'멤버십','아파트 관리비':'주거','전기요금':'공과금','도시가스':'공과금','수도요금':'공과금','보험료':'보험','SKT':'통신','KT':'통신','LG U+':'통신','휴대폰':'통신','인터넷':'통신','IPTV':'통신'};
export function inferFixedCostCategory(name=''){const hit=Object.keys(categoryAliases).find(k=>normalize(name).includes(normalize(k)));return categoryAliases[hit]||'기타';}
export function normalizeFixedCost(item,cardId=''){return {id:item.id||crypto.randomUUID(),name:String(item.name||'').trim(),category:item.category||inferFixedCostCategory(item.name),amount:item.amount===null||item.amount===''?null:Number(item.amount||0),cardId:item.cardId||cardId,day:Number(item.day||1),paymentMethod:item.paymentMethod||'잘 모르겠음',inclusion:item.inclusion||'모름',memo:item.memo||'',changeStatus:item.changeStatus||'current'};}
function modeFor(item){if(item.paymentMethod==='앱스토어 결제')return 'appstore';if(['카드 자동결제','공식 홈페이지 정기결제','자동납부'].includes(item.paymentMethod))return 'recurring';if(item.paymentMethod==='네이버페이')return 'naver-plus';return 'direct';}
function capKey(r){return r?.b?.capGroup?String(r.card.id)+':'+r.b.capGroup:null;}
function applySharedCaps(result,used){const key=capKey(result);if(!key||result.value===null||result.b.monthlyCap===null)return result;const cap=result.b.monthlyCap;const left=Math.max(0,cap-(used.get(key)||0));const value=Math.min(result.value,left);used.set(key,(used.get(key)||0)+value);return value===result.value?result:{...result,value,eligible:value>0,notes:[...result.notes,'같은 영역 월 통합 한도 '+money(cap)+'원 중 '+money(left)+'원 남음']};}
export function analyzeFixedCosts(cards,items,date=new Date()){const normalized=items.map(x=>normalizeFixedCost(x)).filter(x=>x.name);const used=new Map();const analyses=normalized.map(item=>{const results=compareBenefits(cards,catalog,status,item.name,item.amount,modeFor(item),date,[],{assumePreviousSpend:true}).map(r=>applySharedCaps(r,used));const current=results.find(r=>r.card.id===item.cardId);const eligible=results.filter(r=>r.eligible&&r.value!==null).sort((a,b)=>(b.value??-1)-(a.value??-1));const best=eligible[0];const currentValue=current?.value??null;const bestValue=best?.value??null;const gap=currentValue!==null&&bestValue!==null?bestValue-currentValue:null;let state='확인 필요',strength='확인 필요',recommendation=best?.card||null;if(!item.amount||!current||!best||bestValue===null)state='데이터 부족';else if(best.card.id===item.cardId){state='최적';strength='유지 가능';recommendation=current.card;}else if(gap!==null&&gap<=100){state='비슷함';strength='유지 가능';recommendation=current.card;}else if(gap!==null&&gap>0){state='변경 추천';strength=currentValue===0&&gap>=1000?'강력 추천':'추천';}else{state='확인 필요';recommendation=current?.card||best?.card;}const reason=best?.b?best.reason+' · '+(best.notes?.find(n=>n.includes('전월'))||'전월실적 조건 확인')+(best.b.conditions?.[0]?' · '+best.b.conditions[0]:''):'공식 조건 확인 필요';return {item,current,best,state,strength,recommendation,currentValue,bestValue,gap,monthlySaving:state==='변경 추천'?Math.max(0,gap||0):0,reason,sharedCap:best?.b?.capGroup&&best?.b?.monthlyCap!==null?'관련 혜택은 월 통합 한도 '+money(best.b.monthlyCap)+'원입니다.':''};});const summary=analyses.reduce((s,a)=>({...s,total:s.total+1,[a.state]:(s[a.state]||0)+1,saving:s.saving+a.monthlySaving}),{total:0,최적:0,'변경 추천':0,비슷함:0,'확인 필요':0,'데이터 부족':0,saving:0});return {analyses,summary};}
export function fixedCostItems(cards){return cards.flatMap(card=>card.autopayItems.map(item=>normalizeFixedCost(item,card.id)));}
export function fixedCostReason(a){if(a.state==='최적')return '현재 카드가 가장 유리합니다.';if(a.state==='비슷함')return '혜택 차이는 월 '+money(a.gap||0)+'원으로 작아 현재 카드 유지도 괜찮습니다.';if(a.state==='데이터 부족')return '금액·상품·결제방식 또는 공식 조건을 확인해주세요.';return (a.best?.card.displayName||'추천 카드')+'로 변경하면 월 약 '+money(a.monthlySaving)+'원 절약 가능';}