import {useState,useRef,useEffect} from 'react';
import {Home,Search,CreditCard,CalendarDays,Plus,ChevronRight,ArrowUpRight,ArrowLeft,Check,Download,Upload,Star,Trash2,Pencil,Wallet,Info,Bookmark,Settings2} from 'lucide-react';
import CardVisual from './components/CardVisual';
import Sheet from './components/Sheet';
import {useCardStore} from './hooks/useCardStore';
import {money,percent,remaining,scheduled} from './utils/finance';
import {validateData,STORAGE_KEY} from './utils/storage';
import {OfficialBenefits,ProductSettings,RecommendationResults,officialSummary} from './components/OfficialBenefits';
import {previousMonth} from './utils/benefits'; import FixedCostAnalysis from './components/FixedCostAnalysis'; import {fixedCostItems,analyzeFixedCosts} from './utils/fixedCosts';
const tabs=[['home',Home,'홈'],['recommend',Search,'추천'],['cards',CreditCard,'카드'],['autopay',CalendarDays,'고정비']];
const categories=['통신','주거','공과금','보험','구독','멤버십','교육','기타'];
function Amount({label,value,onChange,required=false}){return <label className="field">{label}<div className="amount-field"><input aria-label={label} inputMode="numeric" required={required} value={value===''?'':money(value)} onChange={e=>{const v=e.target.value.replace(/\D/g,'').slice(0,12);onChange(v===''?'':Number(v));}} placeholder="0"/><span>원</span></div></label>;}
function CardEditor({card,onSave}){
 const [draft,setDraft]=useState(structuredClone(card));const field=(k,v)=>setDraft(d=>({...d,[k]:v}));
 return <form onSubmit={e=>{e.preventDefault();onSave({...draft,displayName:draft.displayName.trim(),monthlyGoalKRW:Number(draft.monthlyGoalKRW),benefitSummary:draft.benefitSummary.filter(s=>s.trim()),merchantRules:draft.merchantRules.filter(r=>r.benefitLabel.trim())});}}>
 <label className="field">카드 이름<input required maxLength={80} value={draft.displayName} onChange={e=>field('displayName',e.target.value)}/></label><label className="field">Edition<input value={draft.edition} onChange={e=>field('edition',e.target.value)}/></label><Amount label="월 목표 실적" required value={draft.monthlyGoalKRW} onChange={v=>field('monthlyGoalKRW',v)}/>
 <label className="field">카드 디자인 라벨<input maxLength={30} value={draft.visual.label} onChange={e=>field('visual',{...draft.visual,label:e.target.value})}/></label>
 <ProductSettings card={draft} onChange={field}/><h3>나의 혜택 메모</h3><p className="muted">기존 입력값을 보관합니다. 공식 수치나 계산에 덮어쓰지 않습니다.</p>{draft.benefitSummary.map((b,i)=><div className="edit-row" key={i}><input aria-label={`혜택 ${i+1}`} value={b} onChange={e=>field('benefitSummary',draft.benefitSummary.map((x,j)=>j===i?e.target.value:x))}/><button type="button" className="icon-button" aria-label={`혜택 ${i+1} 삭제`} onClick={()=>field('benefitSummary',draft.benefitSummary.filter((_,j)=>i!==j))}><Trash2 size={18}/></button></div>)}<button className="text-button" type="button" onClick={()=>field('benefitSummary',[...draft.benefitSummary,''])}><Plus size={16}/> 혜택 추가</button>
 <h3>나의 사용처 참고</h3><p className="fine">개인 규칙은 참고로 표시하며 공식 금액 비교에는 사용하지 않습니다.</p>{draft.merchantRules.map((r,i)=><div className="rule-editor" key={i}><div className="section-title"><b>추천 규칙 {i+1}</b><button type="button" className="icon-button" aria-label={`규칙 ${i+1} 삭제`} onClick={()=>field('merchantRules',draft.merchantRules.filter((_,j)=>j!==i))}><Trash2 size={18}/></button></div>{[['benefitLabel','추천 이유'],['keywords','키워드 (쉼표로 구분)'],['priority','우선순위']].map(([key,label])=><label className="field" key={key}>{label}<input aria-label={`${label} ${i+1}`} type={key==='priority'?'number':'text'} inputMode={key==='priority'?'numeric':undefined} value={key==='keywords'?r[key].join(','):r[key]} onChange={e=>field('merchantRules',draft.merchantRules.map((x,j)=>j===i?{...x,[key]:key==='keywords'?e.target.value.split(','):key==='priority'?Number(e.target.value):e.target.value}:x))}/></label>)}</div>)}<button className="text-button" type="button" onClick={()=>field('merchantRules',[...draft.merchantRules,{keywords:[],benefitLabel:'',priority:10}])}><Plus size={16}/> 추천 규칙 추가</button>
 <label className="field">사용자 메모<textarea rows={3} value={draft.memo} onChange={e=>field('memo',e.target.value)}/></label><button className="primary" disabled={!draft.displayName.trim()||!draft.monthlyGoalKRW}>변경사항 저장</button></form>;
}
function AutopayEditor({cards,item,onSave,onDelete}){
 const [d,setD]=useState(item||{id:crypto.randomUUID(),name:'',category:'구독',amount:'',cardId:cards[0].id,day:1,inclusion:'모름',paymentMethod:'잘 모르겠음',changeStatus:'current',memo:''});const f=(k,v)=>setD(s=>({...s,[k]:v}));
 return <form onSubmit={e=>{e.preventDefault();onSave({...d,name:d.name.trim(),amount:d.amount===''||d.amount===null?null:Number(d.amount),day:Number(d.day)});}}><label className="field">이름<input required maxLength={80} placeholder="예: 넷플릭스" value={d.name} onChange={e=>f('name',e.target.value)}/></label><div className="form-grid"><label className="field">카테고리<select value={d.category} onChange={e=>f('category',e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="field">결제일<select value={d.day} onChange={e=>f('day',e.target.value)}>{Array.from({length:31},(_,i)=><option value={i+1} key={i}>{i+1}일</option>)}</select></label></div><Amount label="예상 월 금액 (선택)" value={d.amount??''} onChange={v=>f('amount',v)}/><label className="field">결제 카드<select value={d.cardId} onChange={e=>f('cardId',e.target.value)}>{cards.map(c=><option key={c.id} value={c.id}>{c.displayName}</option>)}</select></label><label className="field">실적 포함 여부<select value={d.inclusion} onChange={e=>f('inclusion',e.target.value)}>{['포함','제외','모름'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field">결제 방식<select value={d.paymentMethod||'잘 모르겠음'} onChange={e=>f('paymentMethod',e.target.value)}>{['카드 자동결제','공식 홈페이지 정기결제','앱스토어 결제','네이버페이','KB Pay','자동납부','잘 모르겠음'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field">메모<textarea value={d.memo} onChange={e=>f('memo',e.target.value)}/></label><button className="primary" disabled={!d.name.trim()}>자동결제 저장</button>{item&&<button className="danger-button" type="button" onClick={()=>onDelete(d)}>이 자동결제 삭제</button>}</form>;
}
export default function App(){
 const {data,setData,update,error}=useCardStore();const [tab,setTab]=useState('home'),[detail,setDetail]=useState(null),[modal,setModal]=useState(null),[query,setQuery]=useState(''),[amount,setAmount]=useState(''),[favorite,setFavorite]=useState(''),[favoriteCategory,setFavoriteCategory]=useState('기타'),[toast,setToast]=useState(''),[install,setInstall]=useState(null);const fileRef=useRef();const viewRef=useRef();viewRef.current={tab,detail,modal};
 useEffect(()=>{const h=e=>{e.preventDefault();setInstall(e);};window.addEventListener('beforeinstallprompt',h);return()=>window.removeEventListener('beforeinstallprompt',h);},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),3000);return()=>clearTimeout(t);}},[toast]);
 useEffect(()=>{const onBack=()=>{const view=viewRef.current;if(view?.modal)setModal(null);else if(view?.detail)setDetail(null);else if(view?.tab!=='home'){setTab('home');window.scrollTo(0,0);}window.history.pushState({cardApp:true},'',window.location.href);};window.history.pushState({cardApp:true},'',window.location.href);window.addEventListener('popstate',onBack);return()=>window.removeEventListener('popstate',onBack);},[]);
 const notify=s=>setToast(s);const close=()=>setModal(null);const navigate=t=>{setTab(t);setDetail(null);window.scrollTo(0,0);};
 const patchCard=c=>{update(d=>({...d,cards:d.cards.map(x=>x.id===c.id?c:x)}));close();notify('저장했어요');};
 const backup=()=>{const content=data?JSON.stringify(data,null,2):localStorage.getItem(STORAGE_KEY)||'{}';const url=URL.createObjectURL(new Blob([content],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`내카드-백업-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const restore=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>2000000)throw Error('2MB 이하의 백업 파일을 선택해주세요.');const next=validateData(JSON.parse(await file.text()));setModal({type:'restore',next});}catch(err){notify(err.message);}};
 const saveAutopay=a=>{update(d=>({...d,cards:d.cards.map(c=>({...c,autopayItems:[...c.autopayItems.filter(x=>x.id!==a.id),...(c.id===a.cardId?[(({cardId,...rest})=>rest)(a)]:[])]}))}));close();notify('자동결제를 저장했어요');};
 const restoreInput=<input className="hidden" ref={fileRef} type="file" accept="application/json,.json" onChange={restore}/>;
 if(!data)return <main className="app"><h1>저장 데이터를 확인해주세요</h1><p>저장된 데이터를 읽을 수 없어 원본을 보존했습니다. 백업 파일로 복원할 수 있습니다.</p><button className="primary" onClick={backup}>원본 데이터 다운로드</button><button className="secondary" onClick={()=>fileRef.current.click()}>데이터 복원</button>{restoreInput}{toast&&<p role="alert">{toast}</p>}{modal?.type==='restore'&&<Sheet title="데이터 복원" onClose={close}><button className="primary" onClick={()=>{setData(modal.next);close();}}>백업으로 복원</button></Sheet>}</main>;
 const cards=data.cards;const current=cards.find(c=>c.id===detail);const total=cards.reduce((s,c)=>s+c.currentSpentKRW,0),goal=cards.reduce((s,c)=>s+c.monthlyGoalKRW,0),achieved=cards.filter(c=>remaining(c)===0).length;const allAuto=cards.flatMap(c=>c.autopayItems); const fixedItems=fixedCostItems(cards); const fixedSummary=analyzeFixedCosts(cards,fixedItems).summary;const first=cards.find(c=>remaining(c)>0)||cards[0];
 const insight=remaining(first)===0?`${first.displayName}는 이번 달 목표를 달성했어요.`:scheduled(first)>=remaining(first)?`${first.displayName}는 자동결제 포함 시 목표 달성 예정이에요.`:`${first.displayName} 목표까지 ${money(remaining(first))}원 남았어요.`;
 const addFavorite=value=>{const place=value?.trim();if(place&&!data.favorites.includes(place)){update(d=>({...d,favorites:[...d.favorites,place]}));notify('자주 쓰는 곳에 추가했어요');}};
 const rememberSearch=value=>{const place=value?.trim();if(place)update(d=>({...d,recentSearches:[place,...d.recentSearches.filter(x=>x!==place)].slice(0,10)}));};
 const addCustomMerchant=merchant=>{if(!merchant?.label)return;update(d=>({...d,customMerchants:d.customMerchants.some(x=>x.name===merchant.label)?d.customMerchants:[...d.customMerchants,{id:crypto.randomUUID(),name:merchant.label,category:merchant.category||'기타'}],favorites:d.favorites.includes(merchant.label)?d.favorites:[...d.favorites,merchant.label]}));notify('내 매장으로 등록했어요');};
 const favoriteSection=<section className="favorites"><div className="section-title"><h3>자주 쓰는 곳</h3><button className="text-button" onClick={()=>{setFavorite('');setFavoriteCategory('기타');setModal({type:'favorite'});}}><Plus size={16}/> 추가</button></div>{data.favorites.length?<div className="chips horizontal">{data.favorites.map(f=><button key={f} className="place-chip" onClick={()=>{navigate('recommend');setQuery(f);}}><Star size={14}/>{f}</button>)}</div>:<p className="muted">자주 가는 곳을 추가하고, 한 번에 추천받으세요.</p>}</section>;
 const autoList=c=><div className="autopay-list">{c.autopayItems.map(a=><button className="auto-row" key={a.id} onClick={()=>setModal({type:'autopay',item:{...a,cardId:c.id}})}><span className="auto-icon"><CalendarDays size={19}/></span><span className="auto-name"><b>{a.name}</b><small>매월 {a.day}일 · {a.category} · 실적 {a.inclusion}</small></span><span className="auto-amount">{a.amount===null?'금액 미정':`${money(a.amount)}원`}<ChevronRight size={15}/></span></button>)}</div>;
 return <><div className="app"><header className="topbar"><button className="brand" onClick={()=>navigate('home')}><span className="brand-icon"><CreditCard size={20}/></span>내 카드<span className="brand-dot"/></button><button className="icon-button" aria-label="설정 및 데이터 백업" onClick={()=>setModal({type:'settings'})}><Settings2 size={21}/></button></header>{error&&<p className="error" role="alert">{error}</p>}
 {current?<><button className="text-button back" onClick={()=>setDetail(null)}><ArrowLeft size={18}/> 내 카드</button><h1>{current.displayName}</h1><CardVisual card={current}/><OfficialBenefits card={current} onEdit={()=>setModal({type:'edit',id:current.id})} onHistory={()=>{setAmount(current.history[previousMonth()]??'');setModal({type:'history',id:current.id});}}/><section className="panel"><div className="section-title"><h3>이번 달 실적</h3><span className="badge">{percent(current)}%</span></div><div className="stat-line"><span>현재 직접 입력</span><b>{money(current.currentSpentKRW)}원</b></div><div className="stat-line"><span>예정 자동결제</span><b>+{money(scheduled(current))}원</b></div><div className="stat-line total-line"><span>예상 실적</span><b>{money(current.currentSpentKRW+scheduled(current))}원</b></div><p className="muted">예상 달성률 {Math.round((current.currentSpentKRW+scheduled(current))/current.monthlyGoalKRW*100)}% · 목표 {money(current.monthlyGoalKRW)}원</p><p className="fine">예정액은 등록된 월 금액 기준이며, 이미 입력한 결제가 포함되면 중복될 수 있어요.</p></section><section className="panel"><h3>카드 정보</h3><div className="stat-line"><span>카드사</span><b>{current.issuer}</b></div><div className="stat-line"><span>Edition</span><b>{current.edition||'미입력'}</b></div><h3>나의 혜택 메모 (미검증)</h3><ul className="benefits">{current.benefitSummary.map((b,i)=><li key={i}><Check size={15}/>{b}</li>)}</ul><p className="fine">기존 입력·초기 참고값입니다. 공식 혜택과 분리하여 보관하며 계산에는 사용하지 않습니다.</p><h3>추천 사용처</h3><div className="chips">{[...new Set(current.merchantRules.flatMap(r=>r.keywords))].filter(Boolean).map(k=><button className="place-chip" key={k} onClick={()=>{navigate('recommend');setQuery(k);}}>{k}</button>)}</div></section><section className="panel"><h3>자동결제</h3>{current.autopayItems.length?autoList(current):<p className="muted">등록된 자동결제가 없어요.</p>}<h3>최근 3개월 기록</h3>{Array.from({length:3},(_,i)=>{const dt=new Date();dt.setMonth(dt.getMonth()-i-1,1);const k=`${dt.getFullYear()}-${String(dt.getMonth()+1).padStart(2,'0')}`;return <div className="stat-line" key={k}><span>{k}</span><b>{current.history[k]===undefined?'기록 없음':`${money(current.history[k])}원`}</b></div>;})}<h3>나의 메모</h3><p className="memo">{current.memo||'아직 메모가 없어요.'}</p></section><button className="primary" onClick={()=>setModal({type:'edit',id:current.id})}><Pencil size={18}/> 카드 정보 편집</button></>:
 tab==='home'?<><div className="page-heading"><div><p className="eyebrow">MY LITTLE WALLET</p><h1>이번 달 카드 현황</h1></div><span className="month-pill">{new Date().getMonth()+1}월 <span className="live-dot"/></span></div><button className="pay-now" onClick={()=>navigate('recommend')}><Wallet size={21}/><span><b>지금 뭐로 결제하지?</b><small>매장과 금액으로 바로 추천받기</small></span><ChevronRight size={20}/></button>{fixedItems.length>0&&<button className="fixed-home-summary" onClick={()=>navigate('autopay')}><span><b>고정비 점검</b><small>{fixedSummary['변경 추천']}건 변경 추천 · 월 {fixedSummary.saving.toLocaleString()}원 추가 절약 가능</small></span><ChevronRight size={18}/></button>}<section className="overview"><div className="section-title"><span>이번 달 입력한 실적</span><span className="tiny-label">{cards[0].monthKey.replace('-','. ')}</span></div><div className="overview-number">{money(total)}<span>원</span></div><div className="overview-footer"><span>전체 목표 {money(goal)}원</span><span><b>{achieved}</b> / 4장 달성</span></div><div className="overview-progress"><i style={{width:`${Math.min(100,total/goal*100)}%`}}/></div></section><div className="insight"><span className="insight-icon"><Info size={17}/></span><p>{insight}</p></div><div className="section-title card-list-heading"><h2>내 지갑 <span>4</span></h2><button className="text-button" onClick={()=>navigate('cards')}>카드 관리 <ChevronRight size={15}/></button></div><div className="wallet-list">{cards.map(c=><article className="wallet-item" key={c.id}><CardVisual card={c} onClick={()=>setDetail(c.id)}/><div className="quick-actions">{[10000,50000,100000].map(v=><button key={v} aria-label={`${c.displayName} ${v/10000}만원 추가`} onClick={()=>{update(d=>({...d,cards:d.cards.map(x=>x.id===c.id?{...x,currentSpentKRW:Math.min(999999999999,x.currentSpentKRW+v)}:x)}));notify(`${money(v)}원을 더했어요`);}}>+{v/10000}만</button>)}<button onClick={()=>{setAmount(c.currentSpentKRW);setModal({type:'amount',id:c.id});}}>직접 입력 <Pencil size={12}/></button></div>{scheduled(c)>0&&<p className="forecast">자동결제 포함 예상 <b>{money(c.currentSpentKRW+scheduled(c))}원</b></p>}</article>)}</div>{favoriteSection}<div className="privacy-note"><Bookmark size={14}/> 내 브라우저에 안전하게, 나만의 카드 기록</div></>:
 tab==='recommend'?<><p className="eyebrow">PAYMENT DECISION</p><h1>어디서 결제하세요?</h1><p className="subtitle">매장과 금액만 입력하면 가장 유리한 카드를 보여드려요.</p><form className="search-field" onSubmit={e=>{e.preventDefault();document.querySelector('.recommend-submit')?.click();}}><Search size={22}/><input aria-label="어디서 결제하세요?" placeholder="스타벅스, 쿠팡, 병원, 주유소..." value={query} onChange={e=>setQuery(e.target.value)}/></form><RecommendationResults cards={cards} query={query} onQueryChange={setQuery} onDetail={setDetail} onSearch={rememberSearch} favorites={data.favorites} recentSearches={data.recentSearches} customMerchants={data.customMerchants} onAddFavorite={addFavorite} onAddCustom={addCustomMerchant}/></>:
 tab==='cards'?<><p className="eyebrow">YOUR COLLECTION</p><h1>내 카드 <span className="heading-count">4</span></h1><p className="subtitle">혜택도, 목표도. 나에게 맞게 관리하세요.</p><div className="collection">{cards.map(c=><article key={c.id}><CardVisual card={c} onClick={()=>setDetail(c.id)}/><button className="collection-caption" onClick={()=>setDetail(c.id)}><div><b>{c.displayName}</b><small>{officialSummary(c)}</small></div><ChevronRight size={19}/></button></article>)}</div><section className="panel"><h3>나의 데이터</h3><button className="setting-row" onClick={backup}><Download size={19}/>데이터 백업<ChevronRight size={16}/></button><button className="setting-row" onClick={()=>fileRef.current.click()}><Upload size={19}/>데이터 복원<ChevronRight size={16}/></button></section></>:
 <><p className="eyebrow">MONTHLY ESSENTIALS</p><h1>고정비 / 자동결제</h1><FixedCostAnalysis cards={cards} items={fixedItems} onEdit={item=>setModal({type:'autopay',item})} onComplete={a=>{if(a.best?.card){saveAutopay({...a.item,cardId:a.best.card.id,changeStatus:'completed'});notify('추천 카드로 변경 완료 처리했어요');}}}/><section className="overview"><span>매월 예정된 고정비</span><div className="overview-number">{money(allAuto.reduce((s,a)=>s+(a.amount||0),0))}<span>원</span></div><div className="overview-footer"><span>등록된 자동결제 {allAuto.length}건</span><span>금액 미정 {allAuto.filter(a=>a.amount===null).length}건</span></div></section><button className="primary" onClick={()=>setModal({type:'autopay'})}><Plus size={19}/> 자동결제 추가</button>{allAuto.length?cards.filter(c=>c.autopayItems.length).map(c=><section className="panel" key={c.id}><h3><span className={`color-dot ${c.visual.theme}`}/>{c.displayName}</h3>{autoList(c)}</section>):<div className="search-empty"><span className="empty-icon"><CalendarDays size={31}/></span><h3>매달 나가는 돈, 한눈에</h3><p>통신비, 구독, 관리비를 등록하고<br/>어느 카드로 결제되는지 확인하세요.</p></div>}<p className="fine">자동결제는 관리용 기록이며 실제 결제를 실행하지 않아요. 실적 ‘포함’ 금액만 예상 실적에 더해집니다.</p></>}
 </div><nav className="tabbar" aria-label="하단 메뉴">{tabs.map(([key,Icon,label])=><button key={key} aria-current={tab===key?'page':undefined} className={tab===key?'active':''} onClick={()=>navigate(key)}><span><Icon size={22} strokeWidth={tab===key?2.5:1.8}/></span>{label}</button>)}</nav>{restoreInput}{toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
 {modal&&<Sheet title={{amount:'이번 달 실적 입력',history:'전월 인정 실적 입력',edit:'카드 정보 편집',autopay:modal.item?'자동결제 편집':'자동결제 추가',favorite:'자주 쓰는 곳',settings:'설정 및 데이터',restore:'데이터 복원'}[modal.type]} onClose={close}>
 {modal.type==='amount'&&<form onSubmit={e=>{e.preventDefault();update(d=>({...d,cards:d.cards.map(c=>c.id===modal.id?{...c,currentSpentKRW:Number(amount)}:c)}));close();notify('현재 실적을 변경했어요');}}><p className="muted">이번 달 누적 사용 금액으로 변경합니다.</p><Amount label="현재 실적" value={amount} onChange={setAmount}/><button className="primary">실적 저장</button></form>}
 {modal.type==='history'&&<form onSubmit={e=>{e.preventDefault();update(d=>({...d,cards:d.cards.map(c=>{if(c.id!==modal.id)return c;const history={...c.history};if(amount==='')delete history[previousMonth()];else history[previousMonth()]=Number(amount);return {...c,history};})}));close();notify('전월 기록을 저장했어요');}}><p className="muted">{previousMonth()} 카드사 인정 실적입니다. 빈칸으로 저장하면 미확인 상태로 돌아갑니다.</p><Amount label="전월 인정 실적" value={amount} onChange={setAmount}/><button className="primary">전월 실적 저장</button></form>}
 {modal.type==='edit'&&<CardEditor card={cards.find(c=>c.id===modal.id)} onSave={patchCard}/>}
 {modal.type==='autopay'&&<AutopayEditor cards={cards} item={modal.item} onSave={saveAutopay} onDelete={a=>{update(d=>({...d,cards:d.cards.map(c=>({...c,autopayItems:c.autopayItems.filter(x=>x.id!==a.id)}))}));close();notify('삭제했어요');}}/>}
 {modal.type==='favorite'&&<><form onSubmit={e=>{e.preventDefault();const value=favorite.trim();if(value&&!data.favorites.includes(value)){update(d=>({...d,favorites:[...d.favorites,value],customMerchants:[...d.customMerchants.filter(m=>m.name!==value),{id:crypto.randomUUID(),name:value,category:favoriteCategory}]}));setFavorite('');notify('추가했어요');}}}><label className="field">가게 또는 업종<input placeholder="예: 회사 구내식당" required maxLength={50} value={favorite} onChange={e=>setFavorite(e.target.value)}/></label><label className="field">이 매장은 어떤 업종인가요?<select value={favoriteCategory} onChange={e=>setFavoriteCategory(e.target.value)}>{['기타','음식점','카페','편의점','대형마트','주유','병원','약국','교통','온라인쇼핑','배달','영화','통신'].map(c=><option key={c}>{c}</option>)}</select></label><button className="primary">추가</button></form>{data.favorites.map(f=><div className="setting-row" key={f}>{f}<button className="icon-button" aria-label={`${f} 삭제`} onClick={()=>update(d=>({...d,favorites:d.favorites.filter(x=>x!==f),customMerchants:d.customMerchants.filter(m=>m.name!==f)}))}><Trash2 size={18}/></button></div>)}</>}
 {modal.type==='settings'&&<><p className="muted">기록은 이 브라우저에 저장됩니다. 기기를 바꾸거나 브라우저 데이터를 지우기 전에 백업해주세요.</p><button className="setting-row" onClick={backup}><Download size={20}/> 데이터 백업 <ChevronRight size={18}/></button><button className="setting-row" onClick={()=>fileRef.current.click()}><Upload size={20}/> 데이터 복원 <ChevronRight size={18}/></button><h3>홈 화면에 추가</h3>{install?<button className="primary" onClick={async()=>{await install.prompt();setInstall(null);}}>내 카드 앱 설치</button>:<p className="muted">iPhone: Safari 공유 메뉴 → 홈 화면에 추가<br/>Android: 브라우저 메뉴 → 앱 설치 또는 홈 화면에 추가</p>}<p className="fine">월이 바뀌면 실적은 0원으로 시작하고, 지난달 기록은 자동으로 보관해요.</p></>}
 {modal.type==='restore'&&<><p>현재 기록을 백업 파일의 카드 4장과 자동결제 {modal.next.cards.reduce((s,c)=>s+c.autopayItems.length,0)}건으로 교체합니다.</p><button className="secondary" onClick={backup}>현재 데이터 먼저 백업</button><button className="primary" onClick={()=>{setData(modal.next);setDetail(null);close();notify('데이터를 복원했어요');}}>이 백업으로 복원</button></>}
 </Sheet>}</>;
}
